export type {
  DiagnosticAnswerMap,
  DiagnosticAnswers,
  DiagnosticAppointment,
  DiagnosticAppointmentStatus,
  DiagnosticAvailabilityRule,
  DiagnosticChannel,
  DiagnosticLocale,
  DiagnosticOption,
  DiagnosticProfile,
  DiagnosticQuestion,
  DiagnosticQuestionChannel,
  DiagnosticRecord,
  DiagnosticRoutineStep,
  DiagnosticSettings,
  DiagnosticSlot,
  DiagnosticSlotOverride,
  GoalAnswer,
  HabitsAnswer,
  HairTypeAnswer,
  ScalpAnswer,
} from "@/lib/domain/diagnostic";
