import type { ProductRow } from "@/lib/infrastructure/supabase/types";

/**
 * Fallback local si Supabase n'est pas configuré ou si la table est vide.
 * Miroir du seed SQL dans supabase/seed-products.sql
 */
export const FALLBACK_PRODUCTS: ProductRow[] = [
  {
    id: "00000000-0000-4000-8000-000000000001",
    slug: "beurre-capillaire",
    name: "Beurre Capillaire",
    price: 28.9,
    compare_at_price: null,
    short_description: "Hydrate en profondeur les textures sèches.",
    description:
      "Un beurre riche et onctueux pour nourrir les cheveux texturés en profondeur. Idéal en leave-in, en sealant ou en soin nuit pour retrouver souplesse et éclat.",
    ingredients:
      "Beurre de karité, huile de coco, huile végétale, vitamine E, actifs botaniques.",
    usage:
      "Sur cheveux humides ou secs, prélever une noisette, réchauffer entre les paumes et répartir longueur/pointes. Éviter les racines si le cuir chevelu est gras.",
    image_url: "/images/products/produit-1-beurre.jpg",
    ingredients_image_url: "/images/ingredients/ingredient-1.jpg",
    lifestyle_image_url: "/images/lifestyle/cheveux-pot-alt.jpg",
    category: "hydratation",
    product_type: "hair_care",
    is_bundle: false,
    is_new: false,
    stock: 18,
    shipping_fee: 0,
    qr_url: "",
    universe: "adult",
    color_variants: [],
  },
  {
    id: "00000000-0000-4000-8000-000000000002",
    slug: "demelant-nourrissant",
    name: "Démêlant nourrissant",
    price: 25.9,
    compare_at_price: null,
    short_description: "Démêle en douceur et nourrit les textures.",
    description:
      "Un démêlant nourrissant pensé pour les cheveux bouclés à crépus. Il facilite le démêlage sans casser la fibre et laisse les cheveux souples et brillants.",
    ingredients:
      "Eau de coco, hibiscus, beurre végétal, huiles nourrissantes, actifs démêlants d'origine naturelle.",
    usage:
      "Appliquer section par section sur cheveux mouillés avant le shampoing ou en leave-in léger. Démêler avec les doigts ou un peigne large.",
    image_url: "/images/products/produit-2-demelant.jpg",
    ingredients_image_url: "/images/ingredients/ingredient-2.jpg",
    lifestyle_image_url: "/images/lifestyle/cheveux-spray-alt.jpg",
    category: "demelage",
    product_type: "hair_care",
    is_bundle: false,
    is_new: false,
    stock: 18,
    shipping_fee: 0,
    qr_url: "",
    universe: "adult",
    color_variants: [],
  },
  {
    id: "00000000-0000-4000-8000-000000000003",
    slug: "masque-capillaire",
    name: "Masque Capillaire",
    price: 29.9,
    compare_at_price: null,
    short_description: "Répare et nourrit intensément la fibre.",
    description:
      "Un masque réparateur pour redonner densité et confort aux cheveux fatigués. Sa texture riche enveloppe la fibre pour une réparation visible après quelques utilisations.",
    ingredients:
      "Beurre de karité, coco, cire végétale, huiles fortifiantes, vitamine E.",
    usage:
      "Après le shampoing, appliquer généreusement, laisser poser 15 à 30 minutes sous une charlotte, puis rincer à l'eau tiède.",
    image_url: "/images/products/produit-3-masque.jpg",
    ingredients_image_url: "/images/ingredients/ingredient-3.jpg",
    lifestyle_image_url: "/images/lifestyle/cheveux-pot.jpg",
    category: "soin",
    product_type: "hair_care",
    is_bundle: false,
    is_new: false,
    stock: 18,
    shipping_fee: 0,
    qr_url: "",
    universe: "adult",
    color_variants: [],
  },
  {
    id: "00000000-0000-4000-8000-000000000004",
    slug: "lotion-repousse",
    name: "Lotion Active Repousse",
    price: 32.9,
    compare_at_price: null,
    short_description: "Hydratante et fortifiante pour stimuler la pousse.",
    description:
      "Lotion hydratante et fortifiante pour stimuler la pousse et renforcer le cuir chevelu. Brume fine idéale en soin quotidien ou après un massage du cuir chevelu.",
    ingredients:
      "Coco, gingembre, amla, huiles botaniques, actifs fortifiants.",
    usage:
      "Vaporiser sur le cuir chevelu propre, masser 2 à 3 minutes. Utiliser 3 à 4 fois par semaine pour un résultat optimal.",
    image_url: "/images/products/produit-4-lotion.jpg",
    ingredients_image_url: "/images/ingredients/ingredient-4.jpg",
    lifestyle_image_url: "/images/lifestyle/cheveux-spray.jpg",
    category: "pousse",
    product_type: "hair_care",
    is_bundle: false,
    is_new: false,
    stock: 18,
    shipping_fee: 0,
    qr_url: "",
    universe: "adult",
    color_variants: [],
  },
  {
    id: "00000000-0000-4000-8000-000000000005",
    slug: "savon-solide",
    name: "Savon solide",
    price: 12.9,
    compare_at_price: null,
    short_description: "Nettoie en douceur, à base d'ingrédients naturels.",
    description:
      "Un savon solide doux pour un nettoyage respectueux. Formulé avec des matières premières naturelles pour préserver l'équilibre du cuir chevelu et de la fibre.",
    ingredients: "Coco, beurres végétaux, cauris symboliques de pureté, actifs saponifiés naturels.",
    usage:
      "Faire mousser entre les mains ou directement sur cheveux mouillés, masser le cuir chevelu, rincer abondamment. Suivre d'un soin hydratant.",
    image_url: "/images/products/produit-5-savon.jpg",
    ingredients_image_url: "/images/ingredients/ingredient-5.jpg",
    lifestyle_image_url: null,
    category: "nettoyage",
    product_type: "hair_care",
    is_bundle: false,
    is_new: true,
    stock: 4,
    shipping_fee: 0,
    qr_url: "",
    universe: "adult",
    color_variants: [],
  },
  {
    id: "00000000-0000-4000-8000-000000000006",
    slug: "gamme-complete",
    name: "Gamme complète Awura",
    price: 100,
    compare_at_price: 130.5,
    short_description:
      "Les 5 soins Awura + diagnostic présentiel offert — routine complète pour ta couronne.",
    description:
      "La gamme complète Awura Beauty réunit le savon solide, le démêlant nourrissant, le masque capillaire, la lotion active repousse et le beurre capillaire. Offre exclusive à 100 € (au lieu de 130,50 €) : un diagnostic capillaire présentiel (trichogramme) est offert après ton achat — réserve ton créneau depuis Diagnostic Capillaire → présentiel.",
    ingredients:
      "Les formules des 5 soins Awura : actifs botaniques, beurres et huiles sélectionnés pour cheveux texturés, afro et métissés.",
    usage:
      "Suis la routine recommandée (wash day + entre-deux). Après l’achat, réserve ton diagnostic présentiel gratuit via Diagnostic Capillaire — présentiel.",
    image_url: "/images/products/produit-1-beurre.jpg",
    ingredients_image_url: "/images/ingredients/ingredient-1.jpg",
    lifestyle_image_url: "/images/lifestyle/cheveux-pot.jpg",
    category: "routine",
    product_type: "hair_care",
    is_bundle: true,
    is_new: true,
    stock: 4,
    shipping_fee: 0,
    qr_url: "",
    universe: "adult",
    color_variants: [],
  },
  {
    id: "00000000-0000-4000-8000-000000000007",
    slug: "fibre-bananier-naturelle",
    name: "Fibre de bananier naturelle",
    price: 14.9,
    compare_at_price: null,
    short_description: "Fibre naturelle pour tresses et locs, légère et résistante.",
    description:
      "Fibre de bananier 100% naturelle, idéale pour le tressage protecteur et les locs. Légère, résistante et douce pour la fibre capillaire.",
    ingredients: "Fibre de bananier 100% naturelle.",
    usage:
      "Séparer en mèches fines, tresser avec les cheveux naturels pour un style protecteur. Peut être utilisée humide ou sèche selon la texture désirée.",
    image_url: "/images/products/produit-1-beurre.jpg",
    ingredients_image_url: "",
    lifestyle_image_url: null,
    category: "fibres-de-bananier",
    product_type: "accessory",
    is_bundle: false,
    is_new: true,
    stock: 20,
    shipping_fee: 0,
    qr_url: "",
    universe: "adult",
    color_variants: ["noir", "blond", "acajou"],
  },
  {
    id: "00000000-0000-4000-8000-000000000008",
    slug: "casque-chauffant",
    name: "Casque chauffant",
    price: 39.9,
    compare_at_price: null,
    short_description: "Active la pénétration des soins grâce à une chaleur douce et homogène.",
    description:
      "Casque chauffant pour optimiser la pénétration des soins capillaires (masques, huiles). Chaleur douce et homogène, idéal en complément des soins Awura.",
    ingredients: "",
    usage:
      "Appliquer le soin, enfiler le casque, brancher et régler la durée (15 à 20 minutes). Laisser agir puis rincer.",
    image_url: "/images/products/produit-3-masque.jpg",
    ingredients_image_url: "",
    lifestyle_image_url: null,
    category: "casques-chauffants",
    product_type: "accessory",
    is_bundle: false,
    is_new: true,
    stock: 12,
    shipping_fee: 0,
    qr_url: "",
    universe: "adult",
    color_variants: ["noir", "rose-clair"],
  },
  {
    id: "00000000-0000-4000-8000-000000000009",
    slug: "chouchou-satin",
    name: "Chouchou en satin",
    price: 8.9,
    compare_at_price: null,
    short_description: "Doux pour la fibre, limite la casse liée aux frictions.",
    description:
      "Chouchou en satin doux, réduit les frictions et préserve les longueurs. Idéal pour les coiffures protectrices au quotidien.",
    ingredients: "",
    usage:
      "Utiliser pour attacher les cheveux sans les casser ni les fragiliser, de jour comme de nuit.",
    image_url: "/images/products/produit-2-demelant.jpg",
    ingredients_image_url: "",
    lifestyle_image_url: null,
    category: "accessoires",
    product_type: "accessory",
    is_bundle: false,
    is_new: false,
    stock: 30,
    shipping_fee: 0,
    qr_url: "",
    universe: "adult",
    color_variants: [],
  },
  {
    id: "00000000-0000-4000-8000-00000000000a",
    slug: "peigne-demelant",
    name: "Peigne démêlant à dents larges",
    price: 9.9,
    compare_at_price: null,
    short_description: "Démêle en douceur les textures bouclées à crépues.",
    description:
      "Peigne à dents larges pensé pour les cheveux bouclés à crépus. Démêle en douceur sans casser la fibre, à utiliser avec le démêlant nourrissant Awura.",
    ingredients: "",
    usage:
      "Utiliser sur cheveux humides et imprégnés de démêlant, section par section, en partant des pointes vers les racines.",
    image_url: "/images/products/produit-2-demelant.jpg",
    ingredients_image_url: "",
    lifestyle_image_url: null,
    category: "accessoires",
    product_type: "accessory",
    is_bundle: false,
    is_new: false,
    stock: 25,
    shipping_fee: 0,
    qr_url: "",
    universe: "adult",
    color_variants: [],
  },
  {
    id: "00000000-0000-4000-8000-00000000000b",
    slug: "coussin-satin",
    name: "Taie d'oreiller en satin",
    price: 24.9,
    compare_at_price: null,
    short_description: "Protège cheveux et peau pendant le sommeil, réduit les frictions.",
    description:
      "Taie d'oreiller en satin pour protéger cheveux et peau pendant le sommeil. Réduit les frictions, préserve l'hydratation et limite la casse nocturne.",
    ingredients: "",
    usage:
      "Installer sur l'oreiller habituel et utiliser chaque nuit pour préserver hydratation et coiffure.",
    image_url: "/images/products/produit-4-lotion.jpg",
    ingredients_image_url: "",
    lifestyle_image_url: null,
    category: "accessoires",
    product_type: "accessory",
    is_bundle: false,
    is_new: true,
    stock: 15,
    shipping_fee: 0,
    qr_url: "",
    universe: "adult",
    color_variants: [],
  },
];

export const PRODUCT_CATEGORIES = [
  "hydratation",
  "demelage",
  "soin",
  "pousse",
  "nettoyage",
  "routine",
  "fibres-de-bananier",
  "casques-chauffants",
  "accessoires",
] as const;
